#!/bin/sh
#
# Run this script after the first cvs checkout to build
# makefiles and friends

#PATH="/usr/sepp/bin:$PATH"
#export PATH

vcheck (){
  perl <<PERL
@t = split /\./, "$1";
@v = map { int \$_ } split /\./, (split /\s+/, \`$2\`)[3];
print "$2 = ", (join ".",@v), "  (expecting $1 or later)\n";
\$v = \$t[0]*1000000+\$t[1]*1000+\$t[2] <= \$v[0]*1000000+\$v[1]*1000+\$v[2];
exit \$v
PERL
}

ERROR=0
LIBTOOL_VER="1.5.6"
AUTOMAKE_VER="1.9.2"
AUTOCONF_VER="2.59"
INTLTOOL_VER="0.35.0"

if vcheck $LIBTOOL_VER "libtool --version"
then
  echo "get a copy of GNU libtool >= $LIBTOOL_VER"
  ERROR=1
fi

if vcheck $AUTOMAKE_VER  "automake  --version"
then
  if vcheck $AUTOMAKE_VER  "automake-1.9 --version"
  then
    echo "get a copy of GNU automake >= $AUTOMAKE_VER"
    ERROR=1
  else
    automake=automake-1.9
    aclocal="aclocal-1.9"
    for d in /usr/pack/automake-1.9.5-to/share/aclocal-1.9 /usr/share/aclocal-1.9 /usr/share/aclocal /usr/pack/rrdtool-1.3svn-to/share/aclocal /usr/pack/intltool-0.37.0-to/share/aclocal ; do
      [ -d $d ] && aclocal="$aclocal -I $d"
    done
  fi
else
    automake="automake"
    aclocal="aclocal"
#    aclocal="aclocal -I /usr/pack/libtool-1.5.14-to/share/aclocal"
fi

if vcheck $AUTOCONF_VER "autoconf --version"
then
  echo "get a copy of GNU autoconf >= $autoconf_ver"
  ERROR=1
fi

if vcheck $INTLTOOL_VER "intltoolize --version"
then
  echo "get a copy of GNU intltoolize >= $INTLTOOL_VER"
  ERROR=1
fi
	
if [ $ERROR -ne 0 ]
then
  exit 1
fi

# remove the bits we are going to recreate

echo Removing old Makefiles
touch Makefile
find . -name "Makefile" -or -name "Makefile.in" -print0 | xargs -0 rm 
echo Cleaning out other leftovers
for x in configure install-sh intltool-merge.in rrd_config.h.in \
         missing intltool-update po/Makefile.in.in config.sub \
         intltool-extract intltool-extract.in config.guess \
         depcomp intltool-update.in autom4te.cache \
         intltool-merge compile; do
  [ ! -L $x -a -d $x ] && rm -r "$x"
  [ ! -L $x -a -f $x ] && rm "$x"
done
set -x
intltoolize --automake -c -f
$aclocal
libtoolize --copy --force
autoheader --force  
$aclocal
$automake --foreign --add-missing --force-missing --copy 
autoconf --force

# vim: set syntax=sh :
