#!/bin/sh
set -e
VERSION=`cat VERSION`
NUMVERS=`perl -n -e 'm/NUMVERS=(\d+\.\d+)/ && print $1' configure`
set -x
perl -i -p -e 's/^\$VERSION.+/\$VERSION='$NUMVERS';/' bindings/perl-*/*.pm
perl -i -p -e 's/RRDtool 1\S+/RRDtool '$VERSION'/ && s/Copyright.+?Oetiker.+\d{4}/Copyright by Tobi Oetiker, 1997-2019/' src/*.h src/*.c
perl -i -p -e 's/^Version:.+/Version: '$VERSION'/' rrdtool.spec
perl -i -p -e 's/rrdtool-[\.\d]+\d(pre\d+)?(rc\d+)?/rrdtool-'$VERSION'/g' doc/rrdbuild.pod
./bootstrap
./configure --enable-maintainer-mode
make dist
tar zxvf rrdtool-${VERSION}.tar.gz
cd rrdtool-$VERSION
./configure
make
src/rrdtool
cd ..
echo READY TO DIST ... press ENTER
read x
scp CHANGES rrdtool-$VERSION.tar.gz  oposs@james:public_html/rrdtool/pub
ssh oposs@james "cd public_html/rrdtool/pub/;rm rrdtool.tar.gz;ln -s rrdtool-$VERSION.tar.gz rrdtool.tar.gz"
cd ..

