#!/bin/bash

# fail immediately if any subsequent command fails
set -e

TZ=CET
export TZ

RRDTOOL="$1"
export RRDTOOL

BASEDIR=$(dirname $0)
cd $BASEDIR

./modify1
./modify2
./modify3
./modify4
./modify5
