#!/bin/bash

. $(dirname $0)/functions

BASE=$BASEDIR/modify2-test



$RRDTOOL create ${BASE}a.rrd --start 1300000000 --step 60 DS:a:GAUGE:120:0:U  RRA:AVERAGE:0.5:1:100 RRA:AVERAGE:0.5:5:2 RRA:MIN:0.5:5:2 RRA:MAX:0.5:5:2 RRA:LAST:0.5:5:2 || fail create

# add 50 values to 
N=10
for T in $(seq 1300000020 60 1300003020) ; do
	$RRDTOOL update ${BASE}a.rrd --template a $T:$N || fail update
	let N=$N+10
done

$RRDTOOL dump ${BASE}a.rrd | $DIFF ${BASE}a-create.dump -
report create

$RRDTOOL modify ${BASE}a.rrd ${BASE}b.rrd RRA#1:+10 RRA#2:+10 RRA#3:+10 RRA#4:+10 || fail modify

$RRDTOOL dump ${BASE}b.rrd | $DIFF ${BASE}b-mod1.dump -
report "simultaneously extend aggregate RRAs"

$RRDTOOL modify ${BASE}a.rrd ${BASE}c.rrd RRA:AVERAGE:0.5:2:10 || fail modify
$RRDTOOL dump ${BASE}c.rrd | $DIFF ${BASE}c-mod1.dump -
report "add RRA with intermediate pdp_cnt"

