.\" cgiInit - Initializes cgi library
.\" Copyright (c) 1998  Martin Schulze <joey@infodrom.north.de>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.TH cgiInit 3 "14 February 1998" "Debian GNU/Linux" "Programmer's Manual"
.SH NAME
cgiInit \- Initializes cgi library
.SH SYNOPSYS
.nf
.B #include <cgi.h>
.sp
.BI "char *cgiGetValue(s_cgi **" parms ", const char *" var );
.fi
.SH DESCRIPTION
This routine returns a pointer to the value of a cgi variable.
Encoded characters (%nn) are already decoded.  One must not free the
pointer.

If
.B multiple
fields are used (i.e. a variable that may contain several values) the
value returned contains all these values concatenated together with a
newline character as separator.

.SH "RETURN VALUE"
On success a pointer to a string is returned.  If the variable wasn't
transmitted through CGI or was empty NULL is returned.

.SH "AUTHOR"
This cgi library is written by Martin Schulze
<joey@infodrom.north.de>.  If you have additions or improvements
please get in touch with him.

.SH "SEE ALSO"
.BR cgiDebug (3),
.BR cgiHeader (3),
.BR cgiInit (3).
