=head1 NAME

rrddump - dump the contents of an RRD to XML format

=head1 SYNOPSIS

B<rrdtool> B<dump> S<[B<--no-header>|B<-n>]> I<filename.rrd> E<gt> I<filename.xml>

or 

B<rrdtool> B<dump> S<[B<--no-header>|B<-n>]> I<filename.rrd> I<filename.xml>

=head1 DESCRIPTION

The B<dump> function writes the contents of an B<RRD> in human
readable (?) XML format to a file or to stdout. This format can
be read by rrdrestore. Together they allow you to transfer your
files from one computer architecture to another as well to
manipulate the contents of an B<RRD> file in a somewhat more
convenient manner.


=over 8

=item I<filename.rrd>

The name of the B<RRD> you want to dump.

=item I<filename.xml>

The (optional) filename that you want to write the XML output to.
If not specified, the XML will be printed to stdout.

=item S<[B<--no-header>|B<-n>]>

In rrdtool 1.3, the dump function started producing correct xml-headers.
Unfortunately the rrdtool restore function from the 1.2 series can not
handle these headers. With this option you can supress the creatinon of
the xml headers.

=back

=head1 EXAMPLES

To transfer an RRD between architectures, follow these steps:

=over 4

=item 1.

On the same system where the RRD was created, use B<rrdtool> B<dump>
to export the data to XML format.

=item 2.

Transfer the XML dump to the target system.

=item 3.

Run B<rrdtool> B<restore> to create a new RRD from the XML dump. See
B<rrdrestore> for details.

=back

=head1 AUTHOR

Tobias Oetiker E<lt>tobi@oetiker.chE<gt>

