=head1 NAME

rrdlast - Return the date of the last data sample in an RRD

=head1 SYNOPSIS

B<rrdtool> B<last> I<filename>

=head1 DESCRIPTION

The B<last> function returns the UNIX timestamp of the most recent
update of the RRD.

=over 8

=item I<filename>

The name of the B<RRD> that contains the data.

=back

=head1 AUTHOR

Russ Wright <rwwright@home.com>



