=head1 NAME

rrdrestore - Restore the contents of an RRD from its XML dump format

=head1 SYNOPSIS

B<rrdtool> B<restore> I<filename.xml> I<filename.rrd>
S<[B<--range-check>|B<-r>]>
S<[B<--force-overwrite>|B<-f>]>

=head1 DESCRIPTION

The B<restore> function reads the XML representation of an RRD and converts
it to the native B<RRD> format.

=over 8

=item I<filename.xml>

The name of the B<XML> file you want to restore. The special filename "-" 
(a single dash) is interpreted as standard input. 

In order to support the restore command in pipe mode (especially when
using B<RRDtool> over a network connection), when using "-" as a filename
the end of the file can be signaled either by closing the data
channel after the file has transferred (as would be the case when
using input redirection within a suitable shell) or by sending a
crtl-Z / newline combination. This allows one to send more commands to the
B<RRDtool> server after a restore.

=item I<filename.rrd>

The name of the B<RRD> to restore.

=item B<--range-check>|B<-r>

Make sure the values in the RRAs do not exceed the limits defined for
the various data sources.

=item B<--force-overwrite>|B<-f>

Allows B<RRDtool> to overwrite the destination B<RRD>.

=back

=head1 AUTHOR

Tobias Oetiker <tobi@oetiker.ch>
