# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ../..

prefix = /usr/local/rrdtool-1.1.0
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/rrdtool
pkglibdir = $(libdir)/rrdtool
pkgincludedir = $(includedir)/rrdtool
top_builddir = ../..

ACLOCAL = ${SHELL} /home/oetiker/data/projects/cvs-checkout/rrdtool/program/config/missing --run aclocal
AUTOCONF = ${SHELL} /home/oetiker/data/projects/cvs-checkout/rrdtool/program/config/missing --run autoconf
AUTOMAKE = ${SHELL} /home/oetiker/data/projects/cvs-checkout/rrdtool/program/config/missing --run automake
AUTOHEADER = ${SHELL} /home/oetiker/data/projects/cvs-checkout/rrdtool/program/config/missing --run autoheader

INSTALL = /usr/sepp/bin/ginstall -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = sparc-sun-solaris2.8
AMTAR = ${SHELL} /home/oetiker/data/projects/cvs-checkout/rrdtool/program/config/missing --run tar
ART_LIB_DIR = libraries/libart_lgpl-2.3.7
AS = @AS@
AWK = gawk
CC = gcc
CGI_LIB_DIR = libraries/cgilib-0.4
COMP_PERL = perl_piped perl_shared
CPP = gcc -E
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
ECHO = /usr/ucb/echo
EXEEXT = 
FREETYPE_LIB_DIR = libraries/freetype-2.0.5
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
NROFF = /usr/sepp/bin/gnroff
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = rrdtool
PERL = /usr/bin/perl
PERLFLAGS = 
PERL_MAKE_OPTIONS = 
PNG_LIB_DIR = libraries/libpng-1.2.0
RANLIB = ranlib
SO_EXT = so
STRIP = strip
TCL_LD_SEARCH_FLAGS = 
TCL_PACKAGE_PATH = 
TCL_PREFIX = 
TCL_SHLIB_CFLAGS = 
TCL_SHLIB_LD = 
TCL_SHLIB_SUFFIX = 
TROFF = /usr/sepp/bin/groff
VERSION = 1.1.0
ZLIB_CFLAGS = -g -O2 -Wall -pedantic -Wshadow -Wpointer-arith -Wcast-align -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Winline  -fPIC
ZLIB_LIB_DIR = libraries/zlib-1.1.3
am__include = include
am__quote = 
install_sh = /home/oetiker/data/projects/cvs-checkout/rrdtool/program/config/install-sh

noinst_LTLIBRARIES = librrd_art.la
noinst_PROGRAMS = gen_art_config

BUILT_SOURCES = art_config.h

EXTRA_DIST = \
	libart-config.in	\
	libart-2.0.pc.in


librrd_art_la_SOURCES = \
	art_affine.c \
	art_alphagamma.c \
	art_bpath.c \
	art_gray_svp.c \
	art_misc.c \
	art_pixbuf.c \
	art_rect.c \
	art_rect_svp.c \
	art_rect_uta.c \
	art_render.c \
	art_render_gradient.c \
	art_render_svp.c \
	art_rgb.c \
	art_rgb_affine.c \
	art_rgb_affine_private.c \
	art_rgb_affine_private.h \
	art_rgb_bitmap_affine.c \
	art_rgb_pixbuf_affine.c \
	art_rgb_rgba_affine.c \
	art_rgb_a_affine.c \
	art_rgba.c \
	art_rgb_svp.c \
	art_svp.c \
	art_svp_intersect.c \
	art_svp_ops.c \
	art_svp_point.c \
	art_svp_render_aa.c \
	art_svp_vpath.c \
	art_svp_vpath_stroke.c \
	art_svp_wind.c \
	art_uta.c \
	art_uta_ops.c \
	art_uta_rect.c \
	art_uta_vpath.c \
	art_uta_svp.c \
	art_vpath.c \
	art_vpath_bpath.c \
	art_vpath_dash.c \
	art_vpath_svp.c	\
	libart-features.c


librrd_artincdir = $(includedir)/libart-2.0/libart_lgpl
librrd_artinc_HEADERS = \
	art_affine.h \
	art_alphagamma.h \
	art_bpath.h \
	art_config.h \
	art_filterlevel.h \
	art_gray_svp.h \
	art_misc.h \
	art_pathcode.h \
	art_pixbuf.h \
	art_point.h \
	art_rect.h \
	art_rect_svp.h \
	art_rect_uta.h \
	art_render.h \
	art_render_gradient.h \
	art_render_svp.h \
	art_rgb.h \
	art_rgb_affine.h \
	art_rgb_bitmap_affine.h \
	art_rgb_pixbuf_affine.h \
	art_rgb_rgba_affine.h \
	art_rgb_a_affine.h \
	art_rgb_svp.h \
	art_rgba.h \
	art_svp.h \
	art_svp_intersect.h \
	art_svp_ops.h \
	art_svp_point.h \
	art_svp_render_aa.h \
	art_svp_vpath.h \
	art_svp_vpath_stroke.h \
	art_svp_wind.h \
	art_uta.h \
	art_uta_ops.h \
	art_uta_rect.h \
	art_uta_vpath.h \
	art_uta_svp.h \
	art_vpath.h \
	art_vpath_bpath.h \
	art_vpath_dash.h \
	art_vpath_svp.h	\
	libart.h	\
	libart-features.h


INCLUDES = -I$(top_srcdir) -I$(top_builddir) -DLIBART_COMPILATION
subdir = libraries/libart_lgpl-2.3.7
mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config/config.h
CONFIG_CLEAN_FILES =
LTLIBRARIES = $(noinst_LTLIBRARIES)

librrd_art_la_LDFLAGS =
librrd_art_la_LIBADD =
am_librrd_art_la_OBJECTS = art_affine.lo art_alphagamma.lo art_bpath.lo \
	art_gray_svp.lo art_misc.lo art_pixbuf.lo art_rect.lo \
	art_rect_svp.lo art_rect_uta.lo art_render.lo \
	art_render_gradient.lo art_render_svp.lo art_rgb.lo \
	art_rgb_affine.lo art_rgb_affine_private.lo \
	art_rgb_bitmap_affine.lo art_rgb_pixbuf_affine.lo \
	art_rgb_rgba_affine.lo art_rgb_a_affine.lo art_rgba.lo \
	art_rgb_svp.lo art_svp.lo art_svp_intersect.lo art_svp_ops.lo \
	art_svp_point.lo art_svp_render_aa.lo art_svp_vpath.lo \
	art_svp_vpath_stroke.lo art_svp_wind.lo art_uta.lo \
	art_uta_ops.lo art_uta_rect.lo art_uta_vpath.lo art_uta_svp.lo \
	art_vpath.lo art_vpath_bpath.lo art_vpath_dash.lo \
	art_vpath_svp.lo libart-features.lo
librrd_art_la_OBJECTS = $(am_librrd_art_la_OBJECTS)
noinst_PROGRAMS = gen_art_config$(EXEEXT)
PROGRAMS = $(noinst_PROGRAMS)

gen_art_config_SOURCES = gen_art_config.c
gen_art_config_OBJECTS = gen_art_config.$(OBJEXT)
gen_art_config_LDADD = $(LDADD)
gen_art_config_DEPENDENCIES =
gen_art_config_LDFLAGS =

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)/config
CPPFLAGS = 
LDFLAGS = 
LIBS = -lm 
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
DEP_FILES = $(DEPDIR)/art_affine.Plo \
	$(DEPDIR)/art_alphagamma.Plo \
	$(DEPDIR)/art_bpath.Plo $(DEPDIR)/art_gray_svp.Plo \
	$(DEPDIR)/art_misc.Plo $(DEPDIR)/art_pixbuf.Plo \
	$(DEPDIR)/art_rect.Plo $(DEPDIR)/art_rect_svp.Plo \
	$(DEPDIR)/art_rect_uta.Plo $(DEPDIR)/art_render.Plo \
	$(DEPDIR)/art_render_gradient.Plo \
	$(DEPDIR)/art_render_svp.Plo $(DEPDIR)/art_rgb.Plo \
	$(DEPDIR)/art_rgb_a_affine.Plo \
	$(DEPDIR)/art_rgb_affine.Plo \
	$(DEPDIR)/art_rgb_affine_private.Plo \
	$(DEPDIR)/art_rgb_bitmap_affine.Plo \
	$(DEPDIR)/art_rgb_pixbuf_affine.Plo \
	$(DEPDIR)/art_rgb_rgba_affine.Plo \
	$(DEPDIR)/art_rgb_svp.Plo $(DEPDIR)/art_rgba.Plo \
	$(DEPDIR)/art_svp.Plo \
	$(DEPDIR)/art_svp_intersect.Plo \
	$(DEPDIR)/art_svp_ops.Plo \
	$(DEPDIR)/art_svp_point.Plo \
	$(DEPDIR)/art_svp_render_aa.Plo \
	$(DEPDIR)/art_svp_vpath.Plo \
	$(DEPDIR)/art_svp_vpath_stroke.Plo \
	$(DEPDIR)/art_svp_wind.Plo $(DEPDIR)/art_uta.Plo \
	$(DEPDIR)/art_uta_ops.Plo \
	$(DEPDIR)/art_uta_rect.Plo \
	$(DEPDIR)/art_uta_svp.Plo \
	$(DEPDIR)/art_uta_vpath.Plo $(DEPDIR)/art_vpath.Plo \
	$(DEPDIR)/art_vpath_bpath.Plo \
	$(DEPDIR)/art_vpath_dash.Plo \
	$(DEPDIR)/art_vpath_svp.Plo \
	$(DEPDIR)/gen_art_config.Po \
	$(DEPDIR)/libart-features.Plo
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -g -O2 -Wall -pedantic -Wshadow -Wpointer-arith -Wcast-align -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Winline  -fPIC
DIST_SOURCES = $(librrd_art_la_SOURCES) gen_art_config.c
HEADERS = $(librrd_artinc_HEADERS)

DIST_COMMON = README $(librrd_artinc_HEADERS) AUTHORS COPYING ChangeLog \
	INSTALL Makefile.am Makefile.in NEWS install-sh missing \
	mkinstalldirs
SOURCES = $(librrd_art_la_SOURCES) gen_art_config.c

all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.ac $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  libraries/libart_lgpl-2.3.7/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)
librrd_art.la: $(librrd_art_la_OBJECTS) $(librrd_art_la_DEPENDENCIES) 
	$(LINK)  $(librrd_art_la_LDFLAGS) $(librrd_art_la_OBJECTS) $(librrd_art_la_LIBADD) $(LIBS)

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
gen_art_config$(EXEEXT): $(gen_art_config_OBJECTS) $(gen_art_config_DEPENDENCIES) 
	@rm -f gen_art_config$(EXEEXT)
	$(LINK) $(gen_art_config_LDFLAGS) $(gen_art_config_OBJECTS) $(gen_art_config_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/art_affine.Plo
include $(DEPDIR)/art_alphagamma.Plo
include $(DEPDIR)/art_bpath.Plo
include $(DEPDIR)/art_gray_svp.Plo
include $(DEPDIR)/art_misc.Plo
include $(DEPDIR)/art_pixbuf.Plo
include $(DEPDIR)/art_rect.Plo
include $(DEPDIR)/art_rect_svp.Plo
include $(DEPDIR)/art_rect_uta.Plo
include $(DEPDIR)/art_render.Plo
include $(DEPDIR)/art_render_gradient.Plo
include $(DEPDIR)/art_render_svp.Plo
include $(DEPDIR)/art_rgb.Plo
include $(DEPDIR)/art_rgb_a_affine.Plo
include $(DEPDIR)/art_rgb_affine.Plo
include $(DEPDIR)/art_rgb_affine_private.Plo
include $(DEPDIR)/art_rgb_bitmap_affine.Plo
include $(DEPDIR)/art_rgb_pixbuf_affine.Plo
include $(DEPDIR)/art_rgb_rgba_affine.Plo
include $(DEPDIR)/art_rgb_svp.Plo
include $(DEPDIR)/art_rgba.Plo
include $(DEPDIR)/art_svp.Plo
include $(DEPDIR)/art_svp_intersect.Plo
include $(DEPDIR)/art_svp_ops.Plo
include $(DEPDIR)/art_svp_point.Plo
include $(DEPDIR)/art_svp_render_aa.Plo
include $(DEPDIR)/art_svp_vpath.Plo
include $(DEPDIR)/art_svp_vpath_stroke.Plo
include $(DEPDIR)/art_svp_wind.Plo
include $(DEPDIR)/art_uta.Plo
include $(DEPDIR)/art_uta_ops.Plo
include $(DEPDIR)/art_uta_rect.Plo
include $(DEPDIR)/art_uta_svp.Plo
include $(DEPDIR)/art_uta_vpath.Plo
include $(DEPDIR)/art_vpath.Plo
include $(DEPDIR)/art_vpath_bpath.Plo
include $(DEPDIR)/art_vpath_dash.Plo
include $(DEPDIR)/art_vpath_svp.Plo
include $(DEPDIR)/gen_art_config.Po
include $(DEPDIR)/libart-features.Plo

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`

.c.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CCDEPMODE) $(depcomp) \
	$(LTCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CCDEPMODE = depmode=gcc
uninstall-info-am:
install-librrd_artincHEADERS: $(librrd_artinc_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(librrd_artincdir)
	@list='$(librrd_artinc_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(INSTALL_HEADER) $$d$$p $(DESTDIR)$(librrd_artincdir)/$$f"; \
	  $(INSTALL_HEADER) $$d$$p $(DESTDIR)$(librrd_artincdir)/$$f; \
	done

uninstall-librrd_artincHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(librrd_artinc_HEADERS)'; for p in $$list; do \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " rm -f $(DESTDIR)$(librrd_artincdir)/$$f"; \
	  rm -f $(DESTDIR)$(librrd_artincdir)/$$f; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ../..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(librrd_artincdir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-generic clean-libtool clean-noinstLTLIBRARIES \
	clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-librrd_artincHEADERS

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-info-am uninstall-librrd_artincHEADERS

.PHONY: GTAGS all all-am check check-am clean clean-generic \
	clean-libtool clean-noinstLTLIBRARIES clean-noinstPROGRAMS \
	distclean distclean-compile distclean-depend distclean-generic \
	distclean-libtool distclean-tags distdir dvi dvi-am info \
	info-am install install-am install-data install-data-am \
	install-exec install-exec-am install-info install-info-am \
	install-librrd_artincHEADERS install-man install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool tags uninstall \
	uninstall-am uninstall-info-am uninstall-librrd_artincHEADERS


art_config.h:	gen_art_config
	./gen_art_config > art_config.h
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
