.\" cgiRedirect - Redirect the browser somewhere else
.\" Copyright (c) 1998  Martin Schulze <joey@infodrom.north.de>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.TH cgiRedirect 3 "17 February 1998" "Debian GNU/Linux" "Programmer's Manual"
.SH NAME
cgiRedirect \- Redirect the browser somewhere else
.SH SYNOPSYS
.nf
.B #include <cgi.h>
.sp
.BI "void cgiRedirect(char *" url );
.fi
.SH DESCRIPTION
The
.B cgiRedirect
routine redirects the browser to another
.IR url .
This mechanism may be useful to redirect invalid requests to some
static pages describing the policy.
.SH "RETURN VALUE"
.BR cgiRedirect ()
does not return a value.

.SH "AUTHOR"
This cgi library is written by Martin Schulze
<joey@infodrom.north.de>.  If you have additions or improvements
please get in touch with him.

.SH "SEE ALSO"
.BR cgiInit (3),
.BR cgiHeader (3).
