#!/bin/sh
#
# Run this script after the first cvs checkout to build
# makefiles and friends
set -x
#
find . -name Makefile | xargs rm -f
find . -name Makefile.in | xargs rm -f


# wget ftp://ftp.gnu.org/gnu/libtool/libtool-1.4.2.tar.gz
libtoolize --automake

# wget ftp://sources.redhat.com/pub/automake/automake-1.5.tar.gz
aclocal
autoheader --warnings=all
automake --foreign --add-missing --force-missing --copy 

# wget ftp://ftp.gnu.org/gnu/autoconf/autoconf-2.52.tar.gz
autoconf 


