=head1 NAME

rrdtool graph - Round Robin Database tool grapher functions

WARNING: This is for version 1.1.x which is B<I<BETA>> software.
The software may contain serious bugs. Some of the items
described in here may not yet exist (although this should
be mentioned) or still be in the alpha stage.  As with every
other RRDtool release: use at your own risk.  In contrast with
the stable version of RRDtool, this release may contain bugs
known to the authors.  It is highly recommended that you subscribe
to the mailing list.
