=head1 SEE ALSO

L<rrdgraph> gives an overview of how B<rrdtool graph> works.
L<rrdgraph_data> describes B<DEF>,B<CDEF> and B<VDEF> in detail,
L<rrdgraph_rpn> describes the B<RPN> language used in the B<?DEF> statements,
L<rrdgraph_graph> page describes all of the graph and print functions.

Make sure to read L<rrdgraph_examples> for tipsE<amp>tricks.

=head1 AUTHOR

Program by Tobias Oetiker E<lt>oetiker@ee.ethz.chE<gt>

This manual page by Alex van den Bogaerdt E<lt>alex@ergens.op.het.netE<gt>
